server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shavindi0609/Library-Management-Configurations.git
          search-paths: platform,services

eureka:
  client:
    enabled: false